export const cityData = [{
  children: [{
    codeid: "1101",
    label: "北京",
    parentid: 11,
    value: "北京"
  }],
  codeid: "11",
  label: "北京",
  value: "北京"
}, {
  children: [{
    codeid: "1201",
    label: "天津",
    parentid: 12,
    value: "天津"
  }],
  codeid: "12",
  label: "天津",
  value: "天津"
}, {
  children: [{
    codeid: "1301",
    label: "石家庄",
    parentid: 13,
    value: "石家庄"
  }, {
    codeid: "1302",
    label: "唐山",
    parentid: 13,
    value: "唐山"
  }, {
    codeid: "1303",
    label: "秦皇岛",
    parentid: 13,
    value: "秦皇岛"
  }, {
    codeid: "1304",
    label: "邯郸",
    parentid: 13,
    value: "邯郸"
  }, {
    codeid: "1305",
    label: "邢台",
    parentid: 13,
    value: "邢台"
  }, {
    codeid: "1306",
    label: "保定",
    parentid: 13,
    value: "保定"
  }, {
    codeid: "1307",
    label: "张家口",
    parentid: 13,
    value: "张家口"
  }, {
    codeid: "1308",
    label: "承德",
    parentid: 13,
    value: "承德"
  }, {
    codeid: "1309",
    label: "沧州",
    parentid: 13,
    value: "沧州"
  }, {
    codeid: "1310",
    label: "廊坊",
    parentid: 13,
    value: "廊坊"
  }, {
    codeid: "1311",
    label: "衡水",
    parentid: 13,
    value: "衡水"
  }],
  codeid: "13",
  label: "河北",
  value: "河北"
}, {
  children: [{
    codeid: "1401",
    label: "太原",
    parentid: 14,
    value: "太原"
  }, {
    codeid: "1402",
    label: "大同",
    parentid: 14,
    value: "大同"
  }, {
    codeid: "1403",
    label: "阳泉",
    parentid: 14,
    value: "阳泉"
  }, {
    codeid: "1404",
    label: "长治",
    parentid: 14,
    value: "长治"
  }, {
    codeid: "1405",
    label: "晋城",
    parentid: 14,
    value: "晋城"
  }, {
    codeid: "1406",
    label: "朔州",
    parentid: 14,
    value: "朔州"
  }, {
    codeid: "1407",
    label: "晋中",
    parentid: 14,
    value: "晋中"
  }, {
    codeid: "1408",
    label: "运城",
    parentid: 14,
    value: "运城"
  }, {
    codeid: "1409",
    label: "忻州",
    parentid: 14,
    value: "忻州"
  }, {
    codeid: "1410",
    label: "临汾",
    parentid: 14,
    value: "临汾"
  }, {
    codeid: "1423",
    label: "吕梁",
    parentid: 14,
    value: "吕梁"
  }],
  codeid: "14",
  label: "山西",
  value: "山西"
}, {
  children: [{
    codeid: "1501",
    label: "呼和浩特",
    parentid: 15,
    value: "呼和浩特"
  }, {
    codeid: "1502",
    label: "包头",
    parentid: 15,
    value: "包头"
  }, {
    codeid: "1503",
    label: "乌海",
    parentid: 15,
    value: "乌海"
  }, {
    codeid: "1504",
    label: "赤峰",
    parentid: 15,
    value: "赤峰"
  }, {
    codeid: "1505",
    label: "通辽",
    parentid: 15,
    value: "通辽"
  }, {
    codeid: "1521",
    label: "呼伦贝尔",
    parentid: 15,
    value: "呼伦贝尔"
  }, {
    codeid: "1522",
    label: "兴安",
    parentid: 15,
    value: "兴安"
  }, {
    codeid: "1525",
    label: "锡林郭勒",
    parentid: 15,
    value: "锡林郭勒"
  }, {
    codeid: "1526",
    label: "乌兰察布",
    parentid: 15,
    value: "乌兰察布"
  }, {
    codeid: "1528",
    label: "巴彦淖尔",
    parentid: 15,
    value: "巴彦淖尔"
  }, {
    codeid: "1529",
    label: "阿拉善",
    parentid: 15,
    value: "阿拉善"
  }],
  codeid: "15",
  label: "内蒙古",
  value: "内蒙古"
}, {
  children: [{
    codeid: "2101",
    label: "沈阳",
    parentid: 21,
    value: "沈阳"
  }, {
    codeid: "2102",
    label: "大连",
    parentid: 21,
    value: "大连"
  }, {
    codeid: "2104",
    label: "抚顺",
    parentid: 21,
    value: "抚顺"
  }, {
    codeid: "2105",
    label: "本溪",
    parentid: 21,
    value: "本溪"
  }, {
    codeid: "2106",
    label: "丹东",
    parentid: 21,
    value: "丹东"
  }, {
    codeid: "2107",
    label: "锦州",
    parentid: 21,
    value: "锦州"
  }, {
    codeid: "2108",
    label: "营口",
    parentid: 21,
    value: "营口"
  }, {
    codeid: "2109",
    label: "阜新",
    parentid: 21,
    value: "阜新"
  }, {
    codeid: "2110",
    label: "辽阳",
    parentid: 21,
    value: "辽阳"
  }, {
    codeid: "2111",
    label: "盘锦",
    parentid: 21,
    value: "盘锦"
  }, {
    codeid: "2112",
    label: "铁岭",
    parentid: 21,
    value: "铁岭"
  }, {
    codeid: "2113",
    label: "朝阳",
    parentid: 21,
    value: "朝阳"
  }, {
    codeid: "2114",
    label: "葫芦岛",
    parentid: 21,
    value: "葫芦岛"
  }],
  codeid: "21",
  label: "辽宁",
  value: "辽宁"
}, {
  children: [{
    codeid: "2201",
    label: "长春",
    parentid: 22,
    value: "长春"
  }, {
    codeid: "2202",
    label: "吉林",
    parentid: 22,
    value: "吉林"
  }, {
    codeid: "2203",
    label: "四平",
    parentid: 22,
    value: "四平"
  }, {
    codeid: "2204",
    label: "辽源",
    parentid: 22,
    value: "辽源"
  }, {
    codeid: "2205",
    label: "通化",
    parentid: 22,
    value: "通化"
  }, {
    codeid: "2206",
    label: "白山",
    parentid: 22,
    value: "白山"
  }, {
    codeid: "2207",
    label: "松原",
    parentid: 22,
    value: "松原"
  }, {
    codeid: "2208",
    label: "白城",
    parentid: 22,
    value: "白城"
  }, {
    codeid: "2224",
    label: "延边",
    parentid: 22,
    value: "延边"
  }],
  codeid: "22",
  label: "吉林",
  value: "吉林"
}, {
  children: [{
    codeid: "2301",
    label: "哈尔滨",
    parentid: 23,
    value: "哈尔滨"
  }, {
    codeid: "2302",
    label: "齐齐哈尔",
    parentid: 23,
    value: "齐齐哈尔"
  }, {
    codeid: "2303",
    label: "鸡西",
    parentid: 23,
    value: "鸡西"
  }, {
    codeid: "2304",
    label: "鹤岗",
    parentid: 23,
    value: "鹤岗"
  }, {
    codeid: "2305",
    label: "双鸭山",
    parentid: 23,
    value: "双鸭山"
  }, {
    codeid: "2306",
    label: "大庆",
    parentid: 23,
    value: "大庆"
  }, {
    codeid: "2307",
    label: "伊春",
    parentid: 23,
    value: "伊春"
  }, {
    codeid: "2308",
    label: "佳木斯",
    parentid: 23,
    value: "佳木斯"
  }, {
    codeid: "2309",
    label: "七台河",
    parentid: 23,
    value: "七台河"
  }, {
    codeid: "2310",
    label: "牡丹江",
    parentid: 23,
    value: "牡丹江"
  }, {
    codeid: "2311",
    label: "黑河",
    parentid: 23,
    value: "黑河"
  }, {
    codeid: "2312",
    label: "绥化",
    parentid: 23,
    value: "绥化"
  }],
  codeid: "23",
  label: "黑龙江",
  value: "黑龙江"
}, {
  children: [{
    codeid: "3101",
    label: "上海",
    parentid: 31,
    value: "上海"
  }],
  codeid: "31",
  label: "上海",
  value: "上海"
}, {
  children: [{
    codeid: "3201",
    label: "南京",
    parentid: 32,
    value: "南京"
  }, {
    codeid: "3202",
    label: "无锡",
    parentid: 32,
    value: "无锡"
  }, {
    codeid: "3203",
    label: "徐州",
    parentid: 32,
    value: "徐州"
  }, {
    codeid: "3204",
    label: "常州",
    parentid: 32,
    value: "常州"
  }, {
    codeid: "3205",
    label: "苏州",
    parentid: 32,
    value: "苏州"
  }, {
    codeid: "3206",
    label: "南通",
    parentid: 32,
    value: "南通"
  }, {
    codeid: "3207",
    label: "连云港",
    parentid: 32,
    value: "连云港"
  }, {
    codeid: "3208",
    label: "淮安",
    parentid: 32,
    value: "淮安"
  }, {
    codeid: "3209",
    label: "盐城",
    parentid: 32,
    value: "盐城"
  }, {
    codeid: "3210",
    label: "扬州",
    parentid: 32,
    value: "扬州"
  }, {
    codeid: "3211",
    label: "镇江",
    parentid: 32,
    value: "镇江"
  }, {
    codeid: "3212",
    label: "泰州",
    parentid: 32,
    value: "泰州"
  }, {
    codeid: "3213",
    label: "宿迁",
    parentid: 32,
    value: "宿迁"
  }],
  codeid: "32",
  label: "江苏",
  value: "江苏"
}, {
  children: [{
    codeid: "3301",
    label: "杭州",
    parentid: 33,
    value: "杭州"
  }, {
    codeid: "3302",
    label: "宁波",
    parentid: 33,
    value: "宁波"
  }, {
    codeid: "3303",
    label: "温州",
    parentid: 33,
    value: "温州"
  }, {
    codeid: "3304",
    label: "嘉兴",
    parentid: 33,
    value: "嘉兴"
  }, {
    codeid: "3305",
    label: "湖州",
    parentid: 33,
    value: "湖州"
  }, {
    codeid: "3306",
    label: "绍兴",
    parentid: 33,
    value: "绍兴"
  }, {
    codeid: "3307",
    label: "金华",
    parentid: 33,
    value: "金华"
  }, {
    codeid: "3308",
    label: "衢州",
    parentid: 33,
    value: "衢州"
  }, {
    codeid: "3309",
    label: "舟山",
    parentid: 33,
    value: "舟山"
  }, {
    codeid: "3310",
    label: "台州",
    parentid: 33,
    value: "台州"
  }, {
    codeid: "3311",
    label: "丽水",
    parentid: 33,
    value: "丽水"
  }],
  codeid: "33",
  label: "浙江",
  value: "浙江"
}, {
  children: [{
    codeid: "3401",
    label: "合肥",
    parentid: 34,
    value: "合肥"
  }, {
    codeid: "3402",
    label: "芜湖",
    parentid: 34,
    value: "芜湖"
  }, {
    codeid: "3403",
    label: "蚌埠",
    parentid: 34,
    value: "蚌埠"
  }, {
    codeid: "3404",
    label: "淮南",
    parentid: 34,
    value: "淮南"
  }, {
    codeid: "3405",
    label: "马鞍山",
    parentid: 34,
    value: "马鞍山"
  }, {
    codeid: "3406",
    label: "淮北",
    parentid: 34,
    value: "淮北"
  }, {
    codeid: "3407",
    label: "铜陵",
    parentid: 34,
    value: "铜陵"
  }, {
    codeid: "3408",
    label: "安庆",
    parentid: 34,
    value: "安庆"
  }, {
    codeid: "3410",
    label: "黄山",
    parentid: 34,
    value: "黄山"
  }, {
    codeid: "3411",
    label: "滁州",
    parentid: 34,
    value: "滁州"
  }, {
    codeid: "3412",
    label: "阜阳",
    parentid: 34,
    value: "阜阳"
  }, {
    codeid: "3413",
    label: "宿州",
    parentid: 34,
    value: "宿州"
  }, {
    codeid: "3414",
    label: "巢湖",
    parentid: 34,
    value: "巢湖"
  }, {
    codeid: "3415",
    label: "六安",
    parentid: 34,
    value: "六安"
  }, {
    codeid: "3416",
    label: "亳州",
    parentid: 34,
    value: "亳州"
  }, {
    codeid: "3417",
    label: "池州",
    parentid: 34,
    value: "池州"
  }, {
    codeid: "3418",
    label: "宣城",
    parentid: 34,
    value: "宣城"
  }],
  codeid: "34",
  label: "安徽",
  value: "安徽"
}, {
  children: [{
    codeid: "3501",
    label: "福州",
    parentid: 35,
    value: "福州"
  }, {
    codeid: "3502",
    label: "厦门",
    parentid: 35,
    value: "厦门"
  }, {
    codeid: "3503",
    label: "莆田",
    parentid: 35,
    value: "莆田"
  }, {
    codeid: "3504",
    label: "三明",
    parentid: 35,
    value: "三明"
  }, {
    codeid: "3505",
    label: "泉州",
    parentid: 35,
    value: "泉州"
  }, {
    codeid: "3506",
    label: "漳州",
    parentid: 35,
    value: "漳州"
  }, {
    codeid: "3507",
    label: "南平",
    parentid: 35,
    value: "南平"
  }, {
    codeid: "3508",
    label: "龙岩",
    parentid: 35,
    value: "龙岩"
  }, {
    codeid: "3509",
    label: "宁德",
    parentid: 35,
    value: "宁德"
  }],
  codeid: "35",
  label: "福建",
  value: "福建"
}, {
  children: [{
    codeid: "3601",
    label: "南昌",
    parentid: 36,
    value: "南昌"
  }, {
    codeid: "3602",
    label: "景德镇",
    parentid: 36,
    value: "景德镇"
  }, {
    codeid: "3603",
    label: "萍乡",
    parentid: 36,
    value: "萍乡"
  }, {
    codeid: "3604",
    label: "九江",
    parentid: 36,
    value: "九江"
  }, {
    codeid: "3605",
    label: "新余",
    parentid: 36,
    value: "新余"
  }, {
    codeid: "3606",
    label: "鹰潭",
    parentid: 36,
    value: "鹰潭"
  }, {
    codeid: "3607",
    label: "赣州",
    parentid: 36,
    value: "赣州"
  }, {
    codeid: "3608",
    label: "吉安",
    parentid: 36,
    value: "吉安"
  }, {
    codeid: "3609",
    label: "宜春",
    parentid: 36,
    value: "宜春"
  }, {
    codeid: "3610",
    label: "抚州",
    parentid: 36,
    value: "抚州"
  }, {
    codeid: "3611",
    label: "上饶",
    parentid: 36,
    value: "上饶"
  }],
  codeid: "36",
  label: "江西",
  value: "江西"
}, {
  children: [{
    codeid: "3701",
    label: "济南",
    parentid: 37,
    value: "济南"
  }, {
    codeid: "3702",
    label: "青岛",
    parentid: 37,
    value: "青岛"
  }, {
    codeid: "3703",
    label: "淄博",
    parentid: 37,
    value: "淄博"
  }, {
    codeid: "3704",
    label: "枣庄",
    parentid: 37,
    value: "枣庄"
  }, {
    codeid: "3705",
    label: "东营",
    parentid: 37,
    value: "东营"
  }, {
    codeid: "3706",
    label: "烟台",
    parentid: 37,
    value: "烟台"
  }, {
    codeid: "3707",
    label: "潍坊",
    parentid: 37,
    value: "潍坊"
  }, {
    codeid: "3708",
    label: "济宁",
    parentid: 37,
    value: "济宁"
  }, {
    codeid: "3709",
    label: "泰安",
    parentid: 37,
    value: "泰安"
  }, {
    codeid: "3710",
    label: "威海",
    parentid: 37,
    value: "威海"
  }, {
    codeid: "3711",
    label: "日照",
    parentid: 37,
    value: "日照"
  }, {
    codeid: "3712",
    label: "莱芜",
    parentid: 37,
    value: "莱芜"
  }, {
    codeid: "3713",
    label: "临沂",
    parentid: 37,
    value: "临沂"
  }, {
    codeid: "3714",
    label: "德州",
    parentid: 37,
    value: "德州"
  }, {
    codeid: "3715",
    label: "聊城",
    parentid: 37,
    value: "聊城"
  }, {
    codeid: "3716",
    label: "滨州",
    parentid: 37,
    value: "滨州"
  }, {
    codeid: "3717",
    label: "菏泽",
    parentid: 37,
    value: "菏泽"
  }],
  codeid: "37",
  label: "山东",
  value: "山东"
}, {
  children: [{
    codeid: "4101",
    label: "郑州",
    parentid: 41,
    value: "郑州"
  }, {
    codeid: "4102",
    label: "开封",
    parentid: 41,
    value: "开封"
  }, {
    codeid: "4103",
    label: "洛阳",
    parentid: 41,
    value: "洛阳"
  }, {
    codeid: "4104",
    label: "平顶山",
    parentid: 41,
    value: "平顶山"
  }, {
    codeid: "4105",
    label: "安阳",
    parentid: 41,
    value: "安阳"
  }, {
    codeid: "4106",
    label: "鹤壁",
    parentid: 41,
    value: "鹤壁"
  }, {
    codeid: "4107",
    label: "新乡",
    parentid: 41,
    value: "新乡"
  }, {
    codeid: "4108",
    label: "焦作",
    parentid: 41,
    value: "焦作"
  }, {
    codeid: "4109",
    label: "濮阳",
    parentid: 41,
    value: "濮阳"
  }, {
    codeid: "4110",
    label: "许昌",
    parentid: 41,
    value: "许昌"
  }, {
    codeid: "4111",
    label: "漯河",
    parentid: 41,
    value: "漯河"
  }, {
    codeid: "4112",
    label: "三门峡",
    parentid: 41,
    value: "三门峡"
  }, {
    codeid: "4113",
    label: "南阳",
    parentid: 41,
    value: "南阳"
  }, {
    codeid: "4114",
    label: "商丘",
    parentid: 41,
    value: "商丘"
  }, {
    codeid: "4115",
    label: "信阳",
    parentid: 41,
    value: "信阳"
  }, {
    codeid: "4116",
    label: "周口",
    parentid: 41,
    value: "周口"
  }, {
    codeid: "4117",
    label: "驻马店",
    parentid: 41,
    value: "驻马店"
  }],
  codeid: "41",
  label: "河南",
  value: "河南"
}, {
  children: [{
    codeid: "4201",
    label: "武汉",
    parentid: 42,
    value: "武汉"
  }, {
    codeid: "4202",
    label: "黄石",
    parentid: 42,
    value: "黄石"
  }, {
    codeid: "4203",
    label: "十堰",
    parentid: 42,
    value: "十堰"
  }, {
    codeid: "4205",
    label: "宜昌",
    parentid: 42,
    value: "宜昌"
  }, {
    codeid: "4206",
    label: "襄樊",
    parentid: 42,
    value: "襄樊"
  }, {
    codeid: "4207",
    label: "鄂州",
    parentid: 42,
    value: "鄂州"
  }, {
    codeid: "4208",
    label: "荆门",
    parentid: 42,
    value: "荆门"
  }, {
    codeid: "4209",
    label: "孝感",
    parentid: 42,
    value: "孝感"
  }, {
    codeid: "4210",
    label: "荆州",
    parentid: 42,
    value: "荆州"
  }, {
    codeid: "4211",
    label: "黄冈",
    parentid: 42,
    value: "黄冈"
  }, {
    codeid: "4212",
    label: "咸宁",
    parentid: 42,
    value: "咸宁"
  }, {
    codeid: "4213",
    label: "随州",
    parentid: 42,
    value: "随州"
  }, {
    codeid: "4228",
    label: "恩施",
    parentid: 42,
    value: "恩施"
  }],
  codeid: "42",
  label: "湖北",
  value: "湖北"
}, {
  children: [{
    codeid: "4301",
    label: "长沙",
    parentid: 43,
    value: "长沙"
  }, {
    codeid: "4302",
    label: "株洲",
    parentid: 43,
    value: "株洲"
  }, {
    codeid: "4303",
    label: "湘潭",
    parentid: 43,
    value: "湘潭"
  }, {
    codeid: "4304",
    label: "衡阳",
    parentid: 43,
    value: "衡阳"
  }, {
    codeid: "4305",
    label: "邵阳",
    parentid: 43,
    value: "邵阳"
  }, {
    codeid: "4306",
    label: "岳阳",
    parentid: 43,
    value: "岳阳"
  }, {
    codeid: "4307",
    label: "常德",
    parentid: 43,
    value: "常德"
  }, {
    codeid: "4308",
    label: "张家界",
    parentid: 43,
    value: "张家界"
  }, {
    codeid: "4309",
    label: "益阳",
    parentid: 43,
    value: "益阳"
  }, {
    codeid: "4310",
    label: "郴州",
    parentid: 43,
    value: "郴州"
  }, {
    codeid: "4311",
    label: "永州",
    parentid: 43,
    value: "永州"
  }, {
    codeid: "4312",
    label: "怀化",
    parentid: 43,
    value: "怀化"
  }, {
    codeid: "4313",
    label: "娄底",
    parentid: 43,
    value: "娄底"
  }, {
    codeid: "4331",
    label: "湘西",
    parentid: 43,
    value: "湘西"
  }],
  codeid: "43",
  label: "湖南",
  value: "湖南"
}, {
  children: [{
    codeid: "4401",
    label: "广州",
    parentid: 44,
    value: "广州"
  }, {
    codeid: "4402",
    label: "韶关",
    parentid: 44,
    value: "韶关"
  }, {
    codeid: "4403",
    label: "深圳",
    parentid: 44,
    value: "深圳"
  }, {
    codeid: "4404",
    label: "珠海",
    parentid: 44,
    value: "珠海"
  }, {
    codeid: "4405",
    label: "汕头",
    parentid: 44,
    value: "汕头"
  }, {
    codeid: "4406",
    label: "佛山",
    parentid: 44,
    value: "佛山"
  }, {
    codeid: "4407",
    label: "江门",
    parentid: 44,
    value: "江门"
  }, {
    codeid: "4408",
    label: "湛江",
    parentid: 44,
    value: "湛江"
  }, {
    codeid: "4409",
    label: "茂名",
    parentid: 44,
    value: "茂名"
  }, {
    codeid: "4412",
    label: "肇庆",
    parentid: 44,
    value: "肇庆"
  }, {
    codeid: "4413",
    label: "惠州",
    parentid: 44,
    value: "惠州"
  }, {
    codeid: "4414",
    label: "梅州",
    parentid: 44,
    value: "梅州"
  }, {
    codeid: "4415",
    label: "汕尾",
    parentid: 44,
    value: "汕尾"
  }, {
    codeid: "4416",
    label: "河源",
    parentid: 44,
    value: "河源"
  }, {
    codeid: "4417",
    label: "阳江",
    parentid: 44,
    value: "阳江"
  }, {
    codeid: "4418",
    label: "清远",
    parentid: 44,
    value: "清远"
  }, {
    codeid: "4419",
    label: "东莞",
    parentid: 44,
    value: "东莞"
  }, {
    codeid: "4420",
    label: "中山",
    parentid: 44,
    value: "中山"
  }, {
    codeid: "4451",
    label: "潮州",
    parentid: 44,
    value: "潮州"
  }, {
    codeid: "4452",
    label: "揭阳",
    parentid: 44,
    value: "揭阳"
  }, {
    codeid: "4453",
    label: "云浮",
    parentid: 44,
    value: "云浮"
  }],
  codeid: "44",
  label: "广东",
  value: "广东"
}, {
  children: [{
    codeid: "4501",
    label: "南宁",
    parentid: 45,
    value: "南宁"
  }, {
    codeid: "4502",
    label: "柳州",
    parentid: 45,
    value: "柳州"
  }, {
    codeid: "4503",
    label: "桂林",
    parentid: 45,
    value: "桂林"
  }, {
    codeid: "4504",
    label: "梧州",
    parentid: 45,
    value: "梧州"
  }, {
    codeid: "4505",
    label: "北海",
    parentid: 45,
    value: "北海"
  }, {
    codeid: "4506",
    label: "防城港",
    parentid: 45,
    value: "防城港"
  }, {
    codeid: "4507",
    label: "钦州",
    parentid: 45,
    value: "钦州"
  }, {
    codeid: "4508",
    label: "贵港",
    parentid: 45,
    value: "贵港"
  }, {
    codeid: "4509",
    label: "玉林",
    parentid: 45,
    value: "玉林"
  }, {
    codeid: "4521",
    label: "南宁",
    parentid: 45,
    value: "南宁"
  }, {
    codeid: "4522",
    label: "柳州",
    parentid: 45,
    value: "柳州"
  }, {
    codeid: "4524",
    label: "贺州",
    parentid: 45,
    value: "贺州"
  }, {
    codeid: "4526",
    label: "百色",
    parentid: 45,
    value: "百色"
  }, {
    codeid: "4527",
    label: "河池",
    parentid: 45,
    value: "河池"
  }],
  codeid: "45",
  label: "广西",
  value: "广西"
}, {
  children: [{
    codeid: "4601",
    label: "海南",
    parentid: 46,
    value: "海南"
  }, {
    codeid: "4602",
    label: "海口",
    parentid: 46,
    value: "海口"
  }, {
    codeid: "4603",
    label: "三亚",
    parentid: 46,
    value: "三亚"
  }],
  codeid: "46",
  label: "海南",
  value: "海南"
}, {
  children: [{
    codeid: "5001",
    label: "重庆",
    parentid: 50,
    value: "重庆"
  }],
  codeid: "50",
  label: "重庆",
  value: "重庆"
}, {
  children: [{
    codeid: "5101",
    label: "成都",
    parentid: 51,
    value: "成都"
  }, {
    codeid: "5103",
    label: "自贡",
    parentid: 51,
    value: "自贡"
  }, {
    codeid: "5104",
    label: "攀枝花",
    parentid: 51,
    value: "攀枝花"
  }, {
    codeid: "5105",
    label: "泸州",
    parentid: 51,
    value: "泸州"
  }, {
    codeid: "5106",
    label: "德阳",
    parentid: 51,
    value: "德阳"
  }, {
    codeid: "5107",
    label: "绵阳",
    parentid: 51,
    value: "绵阳"
  }, {
    codeid: "5108",
    label: "广元",
    parentid: 51,
    value: "广元"
  }, {
    codeid: "5109",
    label: "遂宁",
    parentid: 51,
    value: "遂宁"
  }, {
    codeid: "5110",
    label: "内江",
    parentid: 51,
    value: "内江"
  }, {
    codeid: "5111",
    label: "乐山",
    parentid: 51,
    value: "乐山"
  }, {
    codeid: "5113",
    label: "南充",
    parentid: 51,
    value: "南充"
  }, {
    codeid: "5114",
    label: "眉山",
    parentid: 51,
    value: "眉山"
  }, {
    codeid: "5115",
    label: "宜宾",
    parentid: 51,
    value: "宜宾"
  }, {
    codeid: "5116",
    label: "广安",
    parentid: 51,
    value: "广安"
  }, {
    codeid: "5117",
    label: "达州",
    parentid: 51,
    value: "达州"
  }, {
    codeid: "5118",
    label: "雅安",
    parentid: 51,
    value: "雅安"
  }, {
    codeid: "5119",
    label: "巴中",
    parentid: 51,
    value: "巴中"
  }, {
    codeid: "5120",
    label: "资阳",
    parentid: 51,
    value: "资阳"
  }, {
    codeid: "5132",
    label: "阿坝区",
    parentid: 51,
    value: "阿坝区"
  }, {
    codeid: "5133",
    label: "甘孜",
    parentid: 51,
    value: "甘孜"
  }, {
    codeid: "5134",
    label: "凉山",
    parentid: 51,
    value: "凉山"
  }],
  codeid: "51",
  label: "四川",
  value: "四川"
}, {
  children: [{
    codeid: "5201",
    label: "贵阳",
    parentid: 52,
    value: "贵阳"
  }, {
    codeid: "5202",
    label: "六盘水",
    parentid: 52,
    value: "六盘水"
  }, {
    codeid: "5203",
    label: "遵义",
    parentid: 52,
    value: "遵义"
  }, {
    codeid: "5204",
    label: "安顺",
    parentid: 52,
    value: "安顺"
  }, {
    codeid: "5222",
    label: "铜仁",
    parentid: 52,
    value: "铜仁"
  }, {
    codeid: "5223",
    label: "黔西南",
    parentid: 52,
    value: "黔西南"
  }, {
    codeid: "5224",
    label: "毕节",
    parentid: 52,
    value: "毕节"
  }, {
    codeid: "5226",
    label: "黔东南",
    parentid: 52,
    value: "黔东南"
  }, {
    codeid: "5227",
    label: "黔南",
    parentid: 52,
    value: "黔南"
  }],
  codeid: "52",
  label: "贵州",
  value: "贵州"
}, {
  children: [{
    codeid: "5301",
    label: "昆明",
    parentid: 53,
    value: "昆明"
  }, {
    codeid: "5303",
    label: "曲靖",
    parentid: 53,
    value: "曲靖"
  }, {
    codeid: "5304",
    label: "玉溪",
    parentid: 53,
    value: "玉溪"
  }, {
    codeid: "5305",
    label: "保山",
    parentid: 53,
    value: "保山"
  }, {
    codeid: "5321",
    label: "昭通",
    parentid: 53,
    value: "昭通"
  }, {
    codeid: "5323",
    label: "楚雄",
    parentid: 53,
    value: "楚雄"
  }, {
    codeid: "5325",
    label: "红河",
    parentid: 53,
    value: "红河"
  }, {
    codeid: "5326",
    label: "文山",
    parentid: 53,
    value: "文山"
  }, {
    codeid: "5327",
    label: "思茅",
    parentid: 53,
    value: "思茅"
  }, {
    codeid: "5329",
    label: "大理",
    parentid: 53,
    value: "大理"
  }, {
    codeid: "5331",
    label: "德宏",
    parentid: 53,
    value: "德宏"
  }, {
    codeid: "5332",
    label: "丽江",
    parentid: 53,
    value: "丽江"
  }, {
    codeid: "5333",
    label: "怒江",
    parentid: 53,
    value: "怒江"
  }, {
    codeid: "5334",
    label: "迪庆",
    parentid: 53,
    value: "迪庆"
  }, {
    codeid: "5335",
    label: "临沧",
    parentid: 53,
    value: "临沧"
  }],
  codeid: "53",
  label: "云南",
  value: "云南"
}, {
  children: [{
    codeid: "5401",
    label: "拉萨",
    parentid: 54,
    value: "拉萨"
  }, {
    codeid: "5421",
    label: "昌都",
    parentid: 54,
    value: "昌都"
  }, {
    codeid: "5422",
    label: "山南",
    parentid: 54,
    value: "山南"
  }, {
    codeid: "5423",
    label: "日喀则",
    parentid: 54,
    value: "日喀则"
  }, {
    codeid: "5424",
    label: "那曲",
    parentid: 54,
    value: "那曲"
  }, {
    codeid: "5425",
    label: "阿里",
    parentid: 54,
    value: "阿里"
  }, {
    codeid: "5426",
    label: "林芝",
    parentid: 54,
    value: "林芝"
  }],
  codeid: "54",
  label: "西藏",
  value: "西藏"
}, {
  children: [{
    codeid: "6101",
    label: "西安",
    parentid: 61,
    value: "西安"
  }, {
    codeid: "6102",
    label: "铜川",
    parentid: 61,
    value: "铜川"
  }, {
    codeid: "6103",
    label: "宝鸡",
    parentid: 61,
    value: "宝鸡"
  }, {
    codeid: "6104",
    label: "咸阳",
    parentid: 61,
    value: "咸阳"
  }, {
    codeid: "6105",
    label: "渭南",
    parentid: 61,
    value: "渭南"
  }, {
    codeid: "6106",
    label: "延安",
    parentid: 61,
    value: "延安"
  }, {
    codeid: "6107",
    label: "汉中",
    parentid: 61,
    value: "汉中"
  }, {
    codeid: "6108",
    label: "榆林",
    parentid: 61,
    value: "榆林"
  }, {
    codeid: "6109",
    label: "安康",
    parentid: 61,
    value: "安康"
  }, {
    codeid: "6125",
    label: "商洛",
    parentid: 61,
    value: "商洛"
  }],
  codeid: "61",
  label: "陕西",
  value: "陕西"
}, {
  children: [{
    codeid: "6201",
    label: "兰州",
    parentid: 62,
    value: "兰州"
  }, {
    codeid: "6202",
    label: "嘉峪关",
    parentid: 62,
    value: "嘉峪关"
  }, {
    codeid: "6203",
    label: "金昌",
    parentid: 62,
    value: "金昌"
  }, {
    codeid: "6204",
    label: "白银",
    parentid: 62,
    value: "白银"
  }, {
    codeid: "6205",
    label: "天水",
    parentid: 62,
    value: "天水"
  }, {
    codeid: "6221",
    label: "酒泉",
    parentid: 62,
    value: "酒泉"
  }, {
    codeid: "6222",
    label: "张掖",
    parentid: 62,
    value: "张掖"
  }, {
    codeid: "6223",
    label: "武威",
    parentid: 62,
    value: "武威"
  }, {
    codeid: "6224",
    label: "定西",
    parentid: 62,
    value: "定西"
  }, {
    codeid: "6226",
    label: "陇南",
    parentid: 62,
    value: "陇南"
  }, {
    codeid: "6227",
    label: "平凉",
    parentid: 62,
    value: "平凉"
  }, {
    codeid: "6228",
    label: "庆阳",
    parentid: 62,
    value: "庆阳"
  }, {
    codeid: "6229",
    label: "临夏",
    parentid: 62,
    value: "临夏"
  }, {
    codeid: "6230",
    label: "甘南",
    parentid: 62,
    value: "甘南"
  }],
  codeid: "62",
  label: "甘肃",
  value: "甘肃"
}, {
  children: [{
    codeid: "6301",
    label: "西宁",
    parentid: 63,
    value: "西宁"
  }, {
    codeid: "6321",
    label: "海东",
    parentid: 63,
    value: "海东"
  }, {
    codeid: "6322",
    label: "海北",
    parentid: 63,
    value: "海北"
  }, {
    codeid: "6323",
    label: "黄南",
    parentid: 63,
    value: "黄南"
  }, {
    codeid: "6325",
    label: "海南",
    parentid: 63,
    value: "海南"
  }, {
    codeid: "6326",
    label: "果洛",
    parentid: 63,
    value: "果洛"
  }, {
    codeid: "6327",
    label: "玉树",
    parentid: 63,
    value: "玉树"
  }, {
    codeid: "6328",
    label: "海西",
    parentid: 63,
    value: "海西"
  }],
  codeid: "63",
  label: "青海",
  value: "青海"
}, {
  children: [{
    codeid: "6401",
    label: "银川",
    parentid: 64,
    value: "银川"
  }, {
    codeid: "6402",
    label: "石嘴山",
    parentid: 64,
    value: "石嘴山"
  }, {
    codeid: "6403",
    label: "吴忠",
    parentid: 64,
    value: "吴忠"
  }, {
    codeid: "6422",
    label: "固原",
    parentid: 64,
    value: "固原"
  }],
  codeid: "64",
  label: "宁夏回族自治区",
  value: "宁夏回族自治区"
}, {
  children: [{
    codeid: "6501",
    label: "乌鲁木齐",
    parentid: 65,
    value: "乌鲁木齐"
  }, {
    codeid: "6502",
    label: "克拉玛依",
    parentid: 65,
    value: "克拉玛依"
  }, {
    codeid: "6521",
    label: "吐鲁番",
    parentid: 65,
    value: "吐鲁番"
  }, {
    codeid: "6522",
    label: "哈密",
    parentid: 65,
    value: "哈密"
  }, {
    codeid: "6523",
    label: "昌吉",
    parentid: 65,
    value: "昌吉"
  }, {
    codeid: "6527",
    label: "博尔塔拉",
    parentid: 65,
    value: "博尔塔拉"
  }, {
    codeid: "6528",
    label: "巴音郭楞",
    parentid: 65,
    value: "巴音郭楞"
  }, {
    codeid: "6529",
    label: "阿克苏",
    parentid: 65,
    value: "阿克苏"
  }, {
    codeid: "6530",
    label: "克孜勒苏柯尔克孜",
    parentid: 65,
    value: "克孜勒苏柯尔克孜"
  }, {
    codeid: "6531",
    label: "喀什",
    parentid: 65,
    value: "喀什"
  }, {
    codeid: "6532",
    label: "和田",
    parentid: 65,
    value: "和田"
  }, {
    codeid: "6541",
    label: "伊犁",
    parentid: 65,
    value: "伊犁"
  }, {
    codeid: "6542",
    label: "塔城",
    parentid: 65,
    value: "塔城"
  }, {
    codeid: "6543",
    label: "阿勒泰",
    parentid: 65,
    value: "阿勒泰"
  }],
  codeid: "65",
  label: "新疆维吾尔自治区",
  value: "新疆维吾尔自治区"
}]
